spring:
  thymeleaf:
    mode: LEGACYHTML5
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB   #????????????????????????10MB

uploadFolder: D:/upload/